### ISSUE TITLE
Feature: Statistics menu

### ISSUE THREAD

**Issue by Probotus** [BoBoBaSs84/Los.Santos.Dope.Wars#145]
- like found dealers and not found dealers
- most peddled drug and so...
- current level
- current experience
- and so ..

**Comment by BoBoBaSs84** [comment]
This sound cool.

**Comment by BoBoBaSs84** [comment]
I'm closing this due to the lack of time. (-.-)

**Comment by BoBoBaSs84** [comment]
I'm closing this issue due to the lack of time.
