### ISSUE TITLE
Refactor: Abstraction layer

### ISSUE THREAD

**Issue by BoBoBaSs84** [BoBoBaSs84/Los.Santos.Dope.Wars#200]
Was the `Abstraction` layer really a good idea?

It should work like this:
- `Domain` layer -> `Application` layer
- `Application` layer -> `Infrastructure` layer
- `Application` layer -> `Presentation` layer

Maybe another massive refactoring needed...

**Comment by Probotus** [comment]
I think how it currently is, it is not that bad.
Really needed?

**Comment by BoBoBaSs84** [comment]
I'll leave this issue open for now .. maybe revisiting this issue later somehow.
